# Site settings
title:          LightPink Blog
description:    "A simple blog to discuss about my game LightPink"
url: "https://gabryon.gitlab.io/lightpinkblog"
baseurl: ""

# Author
author:
  name:         Gabriele Pappalardo
  url:          https://gitlab.com/gabryon
  email:        leleattolo99@gmail.com
  twitter_username: gabripappa

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  #- jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

disqus:
  shortname: lightpink-game-1

plugins: [jekyll-workbox-plugin]

workbox:
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html